'use client';
import { useEffect, useState } from 'react';
import { SiteHeader } from '@/components/site-header';
type Criterion = { id?: string; name: string; description: string; weight: number; maxScore: number };
export default function RubricPage({ params }: { params: { slug: string } }) {
    const [criteria, setCriteria] = useState<Criterion[]>([]); const [message, setMessage] = useState('');
    useEffect(() => { fetch(`/api/events/${params.slug}`).then((response) => response.json()).then((event) => setCriteria(event.criteria ?? [])); }, [params.slug]);
    function update(index: number, key: keyof Criterion, value: string) { setCriteria((previous) => previous.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: key === 'weight' || key === 'maxScore' ? Number(value) : value } : item)); }
    async function save() { const response = await fetch(`/api/events/${params.slug}/criteria`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ criteria }) }); const result = await response.json(); setMessage(response.ok ? 'Rubric saved.' : result.error); if (response.ok) setCriteria(result); }
    const total = criteria.reduce((sum, criterion) => sum + criterion.weight, 0);
    return <><SiteHeader /><main className="wrap"><div className="page-title"><div className="eyebrow">Organizer · Judging rubric</div><h1>Decide what matters.</h1><p className="muted">Every criterion is scored from zero to its maximum. Weights must add to exactly 100%.</p></div><div className="toolbar"><span className={total === 100 ? 'pill' : 'status'}>Weight total: {total}%</span><button className="button secondary" onClick={() => setCriteria([...criteria, { name: '', description: '', weight: 0, maxScore: 10 }])}>Add criterion</button><button className="button" disabled={total !== 100} onClick={save}>Save rubric</button></div>{criteria.map((criterion, index) => <div className="form-grid form-panel" key={criterion.id ?? index}><label>Name<input className="field" value={criterion.name} onChange={(event) => update(index, 'name', event.target.value)} /></label><label>Description<input className="field" value={criterion.description ?? ''} onChange={(event) => update(index, 'description', event.target.value)} /></label><label>Weight (%)<input className="field" type="number" min="0" max="100" value={criterion.weight} onChange={(event) => update(index, 'weight', event.target.value)} /></label><label>Maximum score<input className="field" type="number" min="1" max="100" value={criterion.maxScore} onChange={(event) => update(index, 'maxScore', event.target.value)} /></label></div>)}{message && <p role="status" className="status">{message}</p>}</main></>;
}