'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { SiteHeader } from '@/components/site-header';
import { Button } from '@/components/ui/button';
export default function NewEventPage() {
    const [message, setMessage] = useState('');
    async function create(event: FormEvent<HTMLFormElement>) {
        event.preventDefault(); const form = new FormData(event.currentTarget);
        const data = { slug: form.get('slug'), name: form.get('name'), description: form.get('description'), startsAt: new Date(String(form.get('startsAt'))).toISOString(), submissionEnds: new Date(String(form.get('submissionEnds'))).toISOString(), judgingEnds: new Date(String(form.get('judgingEnds'))).toISOString(), votingEnds: new Date(String(form.get('votingEnds'))).toISOString(), teamMin: Number(form.get('teamMin')), teamMax: Number(form.get('teamMax')), votingEnabled: form.get('votingEnabled') === 'on', tracks: String(form.get('tracks')).split(',').map((name) => ({ name: name.trim() })).filter((item) => item.name), prizes: String(form.get('prizes')).split(',').filter(Boolean).map((title) => ({ title: title.trim() })), criteria: [{ name: 'Impact', weight: 35, maxScore: 10 }, { name: 'Craft', weight: 25, maxScore: 10 }, { name: 'Originality', weight: 20, maxScore: 10 }, { name: 'Feasibility', weight: 20, maxScore: 10 }] };
        const response = await fetch('/api/events', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json();
        if (!response.ok) { setMessage(result.error ?? 'Unable to create event'); return; }
        location.href = `/organizer/${result.slug}`;
    }
    return <><SiteHeader /><main className="wrap" style={{ maxWidth: 760 }}><div className="page-title"><div className="eyebrow">Organizer · New event</div><h1>Set the ground rules.</h1><p className="muted">Create an event with a weighted starter rubric. You can replace the rubric through the REST API before scoring begins.</p></div><form className="form-panel form-stack" onSubmit={create}><label>Event name<input className="field" name="name" required /></label><label>URL slug<input className="field" name="slug" pattern="[a-z0-9-]+" required /></label><label>Description<textarea className="field" name="description" required /></label><div className="form-grid">{[['startsAt', 'Starts'], ['submissionEnds', 'Submission deadline'], ['judgingEnds', 'Judging deadline'], ['votingEnds', 'Voting deadline']].map(([name, label]) => <label key={name}>{label}<input className="field" type="datetime-local" name={name} required /></label>)}</div><div className="form-grid"><label>Minimum team size<input className="field" type="number" min="1" max="10" name="teamMin" defaultValue="1" /></label><label>Maximum team size<input className="field" type="number" min="1" max="10" name="teamMax" defaultValue="4" /></label></div><label>Tracks (comma separated)<input className="field" name="tracks" defaultValue="Open Tools" required /></label><label>Prizes (comma separated)<input className="field" name="prizes" /></label><label><input type="checkbox" name="votingEnabled" defaultChecked /> Community voting enabled</label><Button type="submit">Create event</Button>{message && <p role="status" className="status">{message}</p>}</form><Link className="muted" href="/dashboard">← Workspace</Link></main></>;
}