import { test, expect, request } from '@playwright/test';
import { createHash, createHmac } from 'node:crypto';

const origin = 'http://localhost:3000';

test('register through export across participant, judge, and organizer roles', async () => {
    const slug = `acceptance-${Date.now()}`;
    const participant = await request.newContext({ baseURL: origin });
    const organizer = await request.newContext({ baseURL: origin });
    const judge = await request.newContext({ baseURL: origin });
    const email = `acceptance-${Date.now()}@dogfood.local`;
    const password = 'acceptance-password-2026';

    const registered = await participant.post('/api/auth/register', { data: { email, name: 'Acceptance Participant', password } });
    expect(registered.status()).toBe(201);
    expect((await participant.post('/api/auth/login', { data: { email, password } })).ok()).toBeTruthy();
    expect((await organizer.post('/api/auth/login', { data: { email: 'organizer@dogfood.local', password: 'dogfood-demo-2026' } })).ok()).toBeTruthy();
    const now = Date.now();
    const createdEvent = await organizer.post('/api/events', { data: { slug, name: 'Acceptance Event', description: 'Automated lifecycle fixture.', startsAt: new Date(now - 60_000).toISOString(), submissionEnds: new Date(now + 3_600_000).toISOString(), judgingEnds: new Date(now + 7_200_000).toISOString(), votingEnds: new Date(now + 7_200_000).toISOString(), tracks: [{ name: 'Open Tools' }], criteria: [{ name: 'Craft', weight: 60, maxScore: 10 }, { name: 'Impact', weight: 40, maxScore: 10 }] } });
    expect(createdEvent.status()).toBe(201);
    const event = await createdEvent.json();
    const teamResponse = await participant.post(`/api/events/${slug}/teams`, { data: { name: `Acceptance-${Date.now()}` } });
    expect(teamResponse.status()).toBe(201);
    const team = await teamResponse.json();
    const submissionResponse = await participant.post(`/api/events/${slug}/submissions`, { data: { teamId: team.id, trackId: event.tracks[0].id, title: 'Acceptance Project', tagline: 'A lifecycle fixture.', description: 'End-to-end behavior test.', submit: true } });
    expect(submissionResponse.status()).toBe(201);
    const submission = await submissionResponse.json();

    const judgesResponse = await organizer.get('/api/judges');
    const judgePool = await judgesResponse.json();
    const selectedJudge = judgePool.find((item: { email: string }) => item.email === 'judge1@dogfood.local');
    const secondJudge = judgePool.find((item: { email: string }) => item.email === 'judge2@dogfood.local');
    const assignmentResponse = await organizer.post(`/api/events/${slug}/assignments`, { data: { mode: 'manual', judgeIds: [selectedJudge.id], submissionIds: [submission.id], perSubmission: 1 } });
    expect(assignmentResponse.status()).toBe(201);
    const assignment = (await assignmentResponse.json()).assignments[0];
    const autoAssignment = await organizer.post(`/api/events/${slug}/assignments`, { data: { mode: 'auto', judgeIds: [selectedJudge.id, secondJudge.id], submissionIds: [submission.id], perSubmission: 2 } });
    expect(autoAssignment.status()).toBe(201);
    expect((await autoAssignment.json()).count).toBe(1);

    expect((await judge.post('/api/auth/login', { data: { email: 'judge1@dogfood.local', password: 'dogfood-demo-2026' } })).ok()).toBeTruthy();
    const rubric = event.criteria as { id: string; maxScore: number }[];
    const values = Object.fromEntries(rubric.map((criterion) => [criterion.id, Math.min(8, criterion.maxScore)]));
    expect((await judge.post('/api/scores', { data: { assignmentId: assignment.id, values, feedback: 'Lifecycle test score' } })).ok()).toBeTruthy();
    const assigned = await organizer.get(`/api/events/${slug}/assignments`);
    const assignedRows = await assigned.json();
    const actualAssignment = assignedRows.find((row: { id: string }) => row.id === assignment.id);
    expect(actualAssignment.score).toBeTruthy();
    expect((await participant.get(`/api/events/${slug}/results`)).status()).toBe(403);
    const snapshot = await organizer.get(`/api/events/${slug}/bulk`);
    expect(snapshot.ok()).toBeTruthy();
    const snapshotData = await snapshot.json();
    expect(snapshotData.scores).toHaveLength(1);
    expect((await organizer.post(`/api/events/${slug}/bulk`, { data: snapshotData })).status()).toBe(201);
    const participantDeniedAssignments = await participant.get(`/api/events/${slug}/assignments`);
    expect(participantDeniedAssignments.status()).toBe(403);
    expect((await participant.get(`/api/events/${slug}/audit`)).status()).toBe(403);
    const concurrentVotes = await Promise.all([participant.post(`/api/events/${slug}/votes`, { data: { submissionId: submission.id } }), participant.post(`/api/events/${slug}/votes`, { data: { submissionId: submission.id } })]);
    expect(concurrentVotes.map((response) => response.status()).sort()).toEqual([201, 409]);

    const draftTeamResponse = await participant.post(`/api/events/${slug}/teams`, { data: { name: `Late-${Date.now()}` } });
    const draftTeam = await draftTeamResponse.json();
    const draft = await participant.post(`/api/events/${slug}/submissions`, { data: { teamId: draftTeam.id, trackId: event.tracks[0].id, title: 'Late Draft', tagline: 'Must miss deadline.', description: 'Draft for boundary check.', submit: false } });
    expect(draft.status()).toBe(201);
    const expired = new Date(Date.now() - 2_000).toISOString();
    const justExpired = new Date(Date.now() - 1_000).toISOString();
    const update = await organizer.patch(`/api/events/${slug}`, { data: { submissionEnds: expired, judgingEnds: justExpired, votingEnds: expired } });
    expect(update.ok()).toBeTruthy();
    const lateSubmit = await participant.post(`/api/events/${slug}/submissions`, { data: { teamId: draftTeam.id, trackId: event.tracks[0].id, title: 'Late Draft', tagline: 'Must miss deadline.', description: 'Draft for boundary check.', submit: true } });
    expect(lateSubmit.status()).toBe(409);
    const lateEdit = await participant.post(`/api/events/${slug}/submissions`, { data: { teamId: draftTeam.id, trackId: event.tracks[0].id, title: 'Late Draft Changed', tagline: 'Edits must also stop.', description: 'Late draft edit.', submit: false } });
    expect(lateEdit.status()).toBe(409);
    const normalized = await organizer.get(`/api/events/${slug}/results`, { headers: { 'x-score-view': 'normalized' } });
    expect(normalized.ok()).toBeTruthy();
    expect((await organizer.post(`/api/events/${slug}/results`)).ok()).toBeTruthy();
    const certificate = await participant.get(`/api/events/${slug}/certificate`);
    expect(certificate.status()).toBe(200);
    expect((await certificate.body()).subarray(0, 4).toString()).toBe('%PDF');
    expect((await organizer.post(`/api/events/${slug}/records`)).status()).toBe(201);
    const records = await organizer.get(`/api/events/${slug}/records`);
    const record = (await records.json())[0];
    const recordHash = createHash('sha256').update(record.payload).digest('hex');
    const signature = createHmac('sha256', 'local-docker-judge-secret-change-for-production').update(recordHash).digest('hex');
    expect(record.recordHash).toBe(recordHash);
    expect(record.signature).toBe(signature);
    const inviteResponse = await organizer.post(`/api/events/${slug}/judge-invites`, { data: { email: 'participant5@dogfood.local' } });
    expect(inviteResponse.status()).toBe(201);
    const invite = await inviteResponse.json();
    const invitee = await request.newContext({ baseURL: origin });
    expect((await invitee.post('/api/auth/login', { data: { email: 'participant5@dogfood.local', password: 'dogfood-demo-2026' } })).ok()).toBeTruthy();
    expect((await invitee.post(`/api/judge-invites/${invite.token}`)).status()).toBe(200);
    expect((await invitee.get(`/api/events/${slug}/assignments`)).status()).toBe(200);
    expect((await invitee.post(`/api/judge-invites/${invite.token}`)).status()).toBe(410);
    const csv = await organizer.get(`/api/events/${slug}/export?type=submissions`);
    expect(csv.ok()).toBeTruthy();
    expect(await csv.text()).toContain('Acceptance Project');
    const scoreCsv = await organizer.get(`/api/events/${slug}/bulk?format=csv&type=scores`);
    expect(scoreCsv.ok()).toBeTruthy();
    expect((await organizer.post(`/api/events/${slug}/bulk?format=csv&type=scores`, { data: await scoreCsv.text(), headers: { 'content-type': 'text/csv' } })).status()).toBe(201);
    expect((await organizer.post(`/api/events/${slug}/bulk?format=csv&type=submissions`, { data: 'teamName,"unterminated', headers: { 'content-type': 'text/csv' } })).status()).toBe(400);

    await participant.dispose(); await organizer.dispose(); await judge.dispose(); await invitee.dispose();
});