'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { SiteHeader } from '@/components/site-header';

type Event = { id: string; slug: string; name: string; tracks: { id: string; name: string }[]; criteria: { id: string; name: string; maxScore: number; weight: number }[] };
type User = { id: string; name: string; role: string };

export default function DashboardPage() {
    const [user, setUser] = useState<User | null>(null); const [events, setEvents] = useState<Event[]>([]); const [slug, setSlug] = useState(''); const [notice, setNotice] = useState(''); const [teamId, setTeamId] = useState(''); const [teamInvite, setTeamInvite] = useState(''); const [inviteToken, setInviteToken] = useState(''); const [teamName, setTeamName] = useState(''); const [assignments, setAssignments] = useState<any[]>([]); const [progress, setProgress] = useState<any>(null);
    const event = events.find((item) => item.slug === slug);
    useEffect(() => { fetch('/api/auth/me').then((response) => response.json()).then((data) => { if (!data.user) { location.href = '/login'; return; } setUser(data.user); }); fetch('/api/events').then((response) => response.json()).then((items) => { setEvents(items); if (items[0]) setSlug(items[0].slug); }); }, []);
    useEffect(() => { if (!user || !event) return; if (user.role === 'JUDGE') { fetch(`/api/events/${event.slug}/assignments`).then((response) => response.json()).then(setAssignments); fetch(`/api/events/${event.slug}/calibration`).then((response) => response.ok ? response.json() : null).then((data) => { if (data?.direction && data.direction !== 'insufficient-data') setNotice(`Your average score is running ${data.direction === 'in-line' ? 'in line' : data.direction} compared to other judges.`); }); } if (['ADMIN', 'ORGANIZER'].includes(user.role)) fetch(`/api/events/${event.slug}/progress`).then((response) => response.ok ? response.json() : null).then(setProgress); }, [user, event]);
    async function createTeam(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch(`/api/events/${slug}/teams`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: teamName }) }); const data = await response.json(); setNotice(response.ok ? 'Team created.' : data.error); if (response.ok) { setTeamId(data.id); setTeamInvite(data.inviteToken); } }
    async function joinTeam(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch(`/api/events/${slug}/teams`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ inviteToken }) }); const data = await response.json(); setNotice(response.ok ? 'Joined team.' : data.error); if (response.ok) setTeamId(data.teamId); }
    async function saveSubmission(formEvent: FormEvent<HTMLFormElement>) { formEvent.preventDefault(); const form = new FormData(formEvent.currentTarget); const submit = form.get('submitProject') === 'true'; const data = Object.fromEntries(form); const response = await fetch(`/api/events/${slug}/submissions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...data, teamId, submit }) }); const result = await response.json(); setNotice(response.ok ? submit ? 'Project submitted.' : 'Draft saved.' : result.error); }
    async function score(formEvent: FormEvent<HTMLFormElement>, assignmentId: string) { formEvent.preventDefault(); const form = new FormData(formEvent.currentTarget); const values = Object.fromEntries(event!.criteria.map((criterion) => [criterion.id, Number(form.get(criterion.id))])); const response = await fetch('/api/scores', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ assignmentId, values, feedback: form.get('feedback'), changeReason: form.get('changeReason') }) }); const data = await response.json(); setNotice(response.ok ? data.calibration === 'insufficient-data' ? 'Score saved.' : `Your average score is running ${data.calibration === 'in-line' ? 'in line' : data.calibration} compared to other judges.` : data.error); }
    return <>
        <SiteHeader />
        <main className="wrap">
            <div className="page-title"><div className="eyebrow">Workspace</div><h1>{user ? `Good to see you, ${user.name}.` : 'Loading workspace…'}</h1><p className="muted">{user?.role ?? ''} · Select an event to continue.</p></div>
            <div className="toolbar"><select className="field" value={slug} onChange={(event) => setSlug(event.target.value)}>{events.map((item) => <option key={item.id} value={item.slug}>{item.name}</option>)}</select><button className="button secondary" onClick={async () => { await fetch('/api/auth/logout', { method: 'POST' }); location.href = '/'; }}>Sign out</button></div>
            {notice && <div className="status">{notice}</div>}
            {event && user?.role === 'JUDGE' && <div className="toolbar"><Link className="button secondary" href={`/judge/${event.slug}/conflicts`}>Declare conflicts</Link></div>}
            {event && user && ['ADMIN', 'ORGANIZER'].includes(user.role) && <div className="toolbar"><Link className="button secondary" href={`/organizer/${event.slug}/conflicts`}>Conflicts</Link><Link className="button secondary" href={`/organizer/${event.slug}/calibration`}>Calibration</Link>{user.role === 'ADMIN' && <Link className="button secondary" href={`/organizer/${event.slug}/score-history`}>Score edit history</Link>}</div>}
            {user?.role === 'PARTICIPANT' && event && <div className="dashboard-grid">
                <section><h2>Start a team</h2><form className="form-stack form-panel" onSubmit={createTeam}><label>Team name<input className="field" value={teamName} onChange={(event) => setTeamName(event.target.value)} required /></label><button className="button">Create team</button></form>{teamInvite && <p className="status">Invite link: <Link href={`/join/${event.slug}/${teamInvite}`}>Open invite</Link></p>}<form className="form-stack form-panel" onSubmit={joinTeam}><label>Invite token<input className="field" value={inviteToken} onChange={(event) => setInviteToken(event.target.value)} required /></label><button className="button secondary">Join team</button></form>{teamId && <form className="form-stack form-panel" onSubmit={saveSubmission}><h2>Project draft</h2><input type="hidden" name="teamId" value={teamId} /><label>Track<select className="field" name="trackId">{event.tracks.map((track) => <option key={track.id} value={track.id}>{track.name}</option>)}</select></label><label>Project title<input className="field" name="title" required /></label><label>Tagline<input className="field" name="tagline" required /></label><label>Description<textarea className="field" name="description" required /></label><label>Repository URL<input className="field" name="repoUrl" type="url" /></label><label>Demo URL<input className="field" name="demoUrl" type="url" /></label><button className="button secondary" type="submit">Save draft</button><button className="button" type="submit" name="submitProject" value="true">Submit project</button><Link className="muted" href={`/api/events/${event.slug}/certificate`}>Download team certificate</Link></form>}</section>
                <section><h2>Public gallery</h2><p className="muted">Find projects and leave constructive feedback.</p><Link className="button" href={`/events/${event.slug}`}>Explore projects →</Link><Link className="button secondary" href={`/events/${event.slug}/results`}>Published results →</Link></section>
            </div>}
            {user?.role === 'JUDGE' && <section><div className="section-head"><h2>My assigned reviews</h2><span className="muted">{assignments.filter((item) => item.score).length} / {assignments.length} complete</span></div>{assignments.map((assignment) => <form className="form-panel form-stack" key={assignment.id} onSubmit={(formEvent) => score(formEvent, assignment.id)}><h3>{assignment.submission.title} · {assignment.submission.team.name}</h3>{event?.criteria.map((criterion) => <label key={criterion.id}>{criterion.name} ({criterion.weight}%)<input className="field" name={criterion.id} type="number" min="0" max={criterion.maxScore} defaultValue={(assignment.score?.values as Record<string, number> | undefined)?.[criterion.id] ?? ''} required /></label>)}<label>Feedback<textarea name="feedback" className="field" defaultValue={assignment.score?.feedback ?? ''} /></label><label>Reason for score change (optional)<textarea name="changeReason" className="field" maxLength={500} /></label><button className="button">Save score</button></form>)}</section>}
            {user && ['ADMIN', 'ORGANIZER'].includes(user.role) && event && <section><div className="section-head"><h2>Judge completion</h2><Link className="button secondary" href={`/organizer/${event.slug}`}>Open event controls →</Link></div>{progress ? <><p>{progress.scored} of {progress.assignments} reviews complete ({progress.percent}%).</p>{progress.judges.map((judge: any) => <p key={judge.id}>{judge.name} · {judge.completed}/{judge.assigned}<div className="bar"><span style={{ width: `${judge.percent}%` }} /></div></p>)}</> : <p className="muted">Progress is available to the event owner or an admin.</p>}</section>}
        </main>
    </>;
}